[workspace]
resolver = "2"
members = ["crates/crabtainer", "crates/crabtainer_init"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true
panic = "abort"

[workspace.package]
license = "Apache-2.0 OR MIT"
version = "0.1.0"
edition = "2024"
authors = ["LisZLisowni2"]