[workspace]
resolver = "2"
members = ["crates/crabtainer", "crates/crabtainer_init"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true
panic = "abort"

[workspace.package]
license = "Apache-2.0"
version = "0.3.2"
edition = "2024"
authors = ["LisZLisowni2"]
repository = "https://github.com/LisZLisowni2/crabtainer"
description = "A lightweight daemonless container engine built from scratch in Rust"
readme = "README.md"
keywords = ["container", "oci", "namespaces", "cgroups", "docker"]
categories = ["command-line-utilities", "os::unix-apis"]